import torch
import gc
import librosa
import tempfile
import torchaudio
import gradio as gr
from transformers import AutoProcessor, AutoModel
from chatterbox.tts import ChatterboxTTS

# 1. Ultravox model and processor loading
try:
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")

    # Load the processor
    # Remove return_attention_mask from here, as it's causing the error.
    # The processor should handle it internally.
    processor = AutoProcessor.from_pretrained(
        "fixie-ai/ultravox-v0_4",
        trust_remote_code=True,
        revision="main"
    )
    print("Ultravox processor loaded successfully.")

    # Load the model with device_map="auto"
    model = AutoModel.from_pretrained(
        "fixie-ai/ultravox-v0_4",
        trust_remote_code=True,
        revision="main",
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto",
        # Add this argument to suppress the LlamaModel warning if desired, not critical for functionality
        # attn_implementation="eager"
    )
    print("Ultravox model loaded successfully with device_map='auto'.")

except Exception as e:
    print(f"Error loading Ultravox model: {e}")
    print("This error usually indicates a memory issue (not enough VRAM/RAM)")
    print("or an incompatibility with how the model's custom code interacts with Transformers/PyTorch's loading mechanism.")
    print("1. Check your GPU memory usage (`nvidia-smi`).")
    print("2. Ensure `accelerate` is installed and up-to-date (`pip install --upgrade accelerate`).")
    print("3. Consider if your environment has enough RAM for initial loading.")
    exit()

# 2. Chatterbox TTS loader (no changes needed here, it works)
class TTS:
    def __init__(self):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model = None

    def load(self):
        if self.model is None:
            print(f"Loading Chatterbox TTS on device: {self.device}")
            self.model = ChatterboxTTS.from_pretrained(device=self.device)
            print("Chatterbox TTS loaded successfully.")
        return True

    def synthesize(self, text: str) -> str:
        self.load()
        wav = self.model.generate(text)
        if not isinstance(wav, torch.Tensor):
            wav = torch.from_numpy(wav)
        if wav.dim() == 1:
            wav = wav.unsqueeze(0)
        tmp = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
        torchaudio.save(tmp.name, wav.cpu(), self.model.sr)
        if self.device == "cuda":
            torch.cuda.empty_cache()
            gc.collect()
        return tmp.name

tts = TTS()

# 3. Speech-to-speech function
def s2s(audio_path: str) -> str:
    if audio_path is None:
        print("No audio input received yet. Waiting for user interaction.")
        return None

    print(f"Processing audio from: {audio_path}")
    audio, sr = librosa.load(audio_path, sr=16000)
    print(f"Audio loaded with sample rate: {sr}")

    turns = [
        {"role": "system", "content": "You are a helpful voice assistant."},
        {"role": "user", "content": ""} # User's speech content is implicitly provided by `audio`
    ]
    print("Conversation turns prepared.")

    # Process audio and generate text using the loaded model
    # REMOVE return_attention_mask=True from here
    inputs = processor(
        audio=audio,
        sampling_rate=sr,
        turns=turns,
        return_tensors="pt"
    )

    # The attention_mask warning will likely still appear here if the processor
    # outputs `input_features` instead of `input_ids` and the model's `generate`
    # expects `input_ids` with an explicit `attention_mask`.
    # Let's check if the 'attention_mask' key is indeed in the 'inputs' dictionary
    # before trying to use it.
    
    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    print("Inputs processed and moved to model device.")

    # Generate the output from the model
    with torch.no_grad():
        print("Generating response from Ultravox model...")
        
        generate_kwargs = {"max_new_tokens": 128}
        
        # Only pass attention_mask if it's explicitly generated by the processor
        if "attention_mask" in inputs:
            generate_kwargs["attention_mask"] = inputs["attention_mask"]

        generated_ids = model.generate(**inputs, **generate_kwargs)

    print("Ultravox model generation complete.")

    # Decode the generated text
    response_text = processor.decode(generated_ids[0], skip_special_tokens=True)
    print(f"Generated text response: {response_text}")

    # Clean up memory
    del inputs
    del generated_ids
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        gc.collect()
        print("GPU cache cleared.")

    # Convert text → speech via Chatterbox
    print("Synthesizing speech with Chatterbox TTS...")
    synthesized_audio_path = tts.synthesize(response_text)
    print(f"Speech synthesis complete. Output audio: {synthesized_audio_path}")
    return synthesized_audio_path

# 4. Gradio Web UI
with gr.Blocks(title="UltraChat S2S Agent") as demo:
    gr.Markdown("# 🎙️ UltraChat: Speech-to-Speech AI Agent")
    audio_in = gr.Audio(sources=["microphone"], type="filepath", label="Your Speech")
    btn = gr.Button("▶️ Talk to AI")
    audio_out = gr.Audio(type="filepath", label="AI Response")
    btn.click(fn=s2s, inputs=audio_in, outputs=audio_out)

if __name__ == "__main__":
    print("Launching Gradio demo...")
    demo.launch(server_name="0.0.0.0", server_port=7860)
